### ISSUE TITLE
Select Visits

### ISSUE THREAD

**Issue by quiquepaz** [quiquepaz/trip#6]
Hammock depending on:
- [ ] Visiting Skye evaluation #3 
- [ ] Crossing to North evaluation #2 
- [ ] Figuring out best destilleries #4 
- [ ] Figuring out list of castles #5
